riddles = {
    "🔑 What has keys but can't open locks?": "piano",
    "🚶‍♂️ The more you take, the more you leave behind. What am I?": "footsteps",
    "💓 What has a heart that doesn’t beat?": "artichoke",
    "🌬️ I speak without a mouth and hear without ears. I have nobody, but I come alive with the wind. What am I?": "echo",
    "✉️ What can travel around the world while staying in the same corner?": "stamp",
    "🏦 I have branches, but no fruit, trunk, or leaves. What am I?": "bank",
    "🌑 The more of this there is, the less you see. What is it?": "darkness",
    "🧽 What gets wetter as it dries?": "towel",
    "🕰️ What has hands but can’t clap?": "clock",
    "🕯️ I’m tall when I’m young, and I’m short when I’m old. What am I?": "candle",
    "🌧️ What comes down but never goes up?": "rain",
    "🥚 What has to be broken before you can use it?": "egg",
    "💨 I’m light as a feather, yet the strongest person can’t hold me for more than 5 minutes. What am I?": "breath",
    "🕳️ What is full of holes but still holds water?": "sponge",
    "🌊 What can run but never walks, has a mouth but never talks, has a bed but never sleeps?": "river",
    "⌨️ I have keys but no locks. I have space but no room. You can enter but can’t go outside. What am I?": "keyboard",
    "📧 What begins with an ‘E’, ends with an ‘E’, but only contains one letter?": "envelope",
    "🤧 What can you catch but not throw?": "cold",
    "🪡 What has one eye but can’t see?": "needle",
    "🧤 What has four fingers and a thumb but isn’t alive?": "glove",
    "🤫 What is so fragile that saying its name breaks it?": "silence",
    "🎂 What goes up but never comes down?": "age",
    "🪟 What invention lets you look right through a wall?": "window",
    "📰 What’s black and white and read all over?": "newspaper",
    "🧶 I’m found in socks, scarves, and mittens; and often in the paws of playful kittens. What am I?": "yarn",
    "🪞 If you drop me I’m sure to crack, but give me a smile and I’ll always smile back. What am I?": "mirror",
    "🌘 The more you have of it, the less you see. What is it?": "darkness",
    "🪙 What has a head, a tail, but no body?": "coin",
    "⚖️ Forward I am heavy, but backward I am not. What am I?": "ton",
    "🍵 What begins with T, ends with T, and has T in it?": "teapot",
    "🎹 What has many keys but can’t open a single lock?": "piano",
    "🗺️ What has cities, but no houses; forests, but no trees; and rivers, but no water?": "map",
    "👻 What room do ghosts avoid?": "living room",
    "🍾 What has a neck but no head?": "bottle",
    "🌫️ The more you have, the less you see. What is it?": "fog",
    "💪 What can you hold in your left hand but not in your right?": "right elbow",
    "🪑 What has legs, but doesn’t walk?": "chair",
    "⏳ What comes once in a minute, twice in a moment, but never in a thousand years?": "m",
    "⏳ What is always in front of you but can’t be seen?": "future",
    "💡 What can fill a room but takes up no space?": "light",
    "🕳️ What gets bigger the more you take away?": "hole",
    "🌬️ What is so light, even the smallest breeze can move it, but yet the strongest man can’t hold it for long?": "breath"
}
